// Code generated by protoc-go-register. DO NOT EDIT.

package protoc

import "reflect"

type MsgType int32
const (
	//Custom MsgType
	MsgTypeBagOpt3		MsgType = 200

	//Auto Generate MsgType
	MsgTypeBagOptGroup0		MsgType = 22
	MsgTypeBagOptGroup0a		MsgType = 23
	MsgTypeBagOpt		MsgType = 201
	MsgTypeBagOptGrpupOne		MsgType = 202
	MsgTypeBagOpt2		MsgType = 300
)

func init() {
	registerMessage(int32(MsgTypeBagOpt), reflect.TypeOf((*BagOpt)(nil)))
}
